# what could arguably be standard

DQUOTE      = %x22                                                  ; # " (Double Quote)
SQUOTE      = %x27                                                  ; # ' (Single Quote)
OR          = "||"                                                  ; 
AND         =  "&&"                                                 ; 
NOT         = "!"                                                   ;  
NOT_EQ      = "!="                                                  ; 
LESS        = "<"                                                   ;
GREATER     = ">"                                                   ;
LESS_EQ     = "<="                                                  ;
GREATER_EQ  = ">="                                                  ;
EQ          = "="                                                   ; 
PLUS        = "+"                                                   ; 
NEG         = "-"                                                   ;   

# what should probably be standard

BOOL        = "true" / "false"                                      ;
NULL        = "null"                                                ;
ALPHANUM    = ALPHA / DIGIT                                         ; # a-z 0-9
INT32       = 1*10DIGIT                                             ; # integer value

# standard ones

CHAR        = %x01-7F                                               ; # any 7-bit US-ASCII character, excluding NULL
VCHAR       = %x21-7E                                               ; # visible (printing) characters
ALPHA       = %x41-5A / %x61-7A                                     ; # A-Z  /  a-z
DIGIT       = %x30-39                                               ; # 0-9 
LWSP        = * WSP                                                 ; 
WSP         = %x20                                                  ; # space
WSP         =/ %x09                                                 ; # horizontal tab
WSP         =/ %x0D %x0A                                            ; # cr lf
WSP         =/ %x0A                                                 ; # lf
